# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json* pnpm-lock.yaml* ./

# Since the repo uses npm, we use npm install (ignore scripts if necessary)
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any ports if needed (not strictly necessary for stdio based MCP)

CMD ["node", "dist/index.js"]
